/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;


import datos.ClienteDAO;
import datos.VehiculoDAO;

import entidades.Cliente;
import entidades.Vehiculo;

import java.util.List;
import entidades.Reserva;
import datos.ReservaDAO;

import java.text.SimpleDateFormat;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author camil
 */
public class FrmReservas extends javax.swing.JInternalFrame {
ReservaDAO dao = new ReservaDAO();
    private int idReserva = 0;
    
    public FrmReservas() {
        
        initComponents();
        
         cargarClientes();
        cargarVehiculos();
        
        listar();
        limpiar();
    }
     public void cargarClientes() {

    cbCliente.removeAllItems();

    ClienteDAO daoCliente = new ClienteDAO();

    List<Cliente> lista = daoCliente.listar();

    for (Cliente c : lista) {

        cbCliente.addItem(
            c.getId() + " - " + c.getNombre()
        );
    }
}
 public void cargarVehiculos() {

    cbVehiculo.removeAllItems();

    VehiculoDAO daoVehiculo = new VehiculoDAO();

    List<Vehiculo> lista = daoVehiculo.listar();

    for (Vehiculo v : lista) {

        cbVehiculo.addItem(
            v.getId() + " - " + v.getMarca()
        );
    }
}
 
 public void listar() {

    

    List<Reserva> lista = dao.listar();

    DefaultTableModel modelo =
        (DefaultTableModel)
        tblReservas.getModel();

    modelo.setRowCount(0);

    Object[] fila = new Object[7];

    for (Reserva r : lista) {

        fila[0] = r.getId();
        fila[1] = r.getClienteId();
        fila[2] = r.getVehiculoId();
        fila[3] = r.getFechaInicio();
        fila[4] = r.getFechaFin();
        fila[5] = r.getEstado();
        fila[6] = r.getFechaCreacion();

        modelo.addRow(fila);
    }
}
 
 public void limpiar() {

    idReserva = 0;

    txtFechaInicio.setText("");
    txtFechaFin.setText("");
    txtFechaCreacion.setText("");

    cbCliente.setSelectedIndex(0);
    cbVehiculo.setSelectedIndex(0);
    cbEstado.setSelectedIndex(0);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox<>();
        cbVehiculo = new javax.swing.JComboBox<>();
        cbEstado = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        txtFechaFin = new javax.swing.JTextField();
        txtFechaCreacion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReservas = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reservas");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel1.setText("RESERVAS");

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 3, 24)); // NOI18N
        jLabel2.setText("RentMovy");

        jLabel3.setText("Cliente :");

        jLabel4.setText("Vehiculo:");

        jLabel5.setText("Estado:");

        cbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Activa", "Finalizada", "Cancelada" }));

        jLabel6.setText("Fecha de Inicio");

        jLabel7.setText("Fecha de Fin");

        jLabel8.setText("Fecha de Creacion");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        tblReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Vehiculo", "Fecha Inicio", "Fecha Fin", "Estado", "Fecha Creacion"
            }
        ));
        tblReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReservasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblReservas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel4)
                                .addGap(32, 32, 32)
                                .addComponent(cbVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(268, 268, 268)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtFechaCreacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                        .addComponent(txtFechaFin, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFechaInicio, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnActualizar)
                                        .addGap(29, 29, 29)
                                        .addComponent(btnEliminar)
                                        .addGap(33, 33, 33)
                                        .addComponent(btnLimpiar)))
                                .addGap(55, 55, 55)
                                .addComponent(jScrollPane1)))))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardar)
                    .addComponent(jLabel8))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(cbVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2)))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnActualizar)
                            .addComponent(btnEliminar)
                            .addComponent(btnLimpiar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
 
    try {

        SimpleDateFormat formato =
            new SimpleDateFormat("yyyy-MM-dd");

        Reserva obj = new Reserva();

        String clienteTexto =
            cbCliente.getSelectedItem().toString();

        int clienteId =
            Integer.parseInt(
                clienteTexto.split(" - ")[0]
            );

        String vehiculoTexto =
            cbVehiculo.getSelectedItem().toString();

        int vehiculoId =
            Integer.parseInt(
                vehiculoTexto.split(" - ")[0]
            );

        obj.setClienteId(clienteId);

        obj.setVehiculoId(vehiculoId);

        obj.setFechaInicio(
            formato.parse(
                txtFechaInicio.getText()
            )
        );

        obj.setFechaFin(
            formato.parse(
                txtFechaFin.getText()
            )
        );

        obj.setEstado(
            cbEstado.getSelectedItem().toString()
        );

        obj.setFechaCreacion(
            formato.parse(
                txtFechaCreacion.getText()
            )
        );

       

       
        
        if (dao.insertar(obj)) {

            JOptionPane.showMessageDialog(
                null,
                "Reserva guardada"
            );

        } else {

            JOptionPane.showMessageDialog(
                null,
                "Error al guardar"
            );
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
            null,
            "Formato incorrecto. Usa yyyy-MM-dd"
        );
    }
    
    
    
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReservasMouseClicked
        int fila = tblReservas.getSelectedRow();

if (fila >= 0) {

    idReserva = Integer.parseInt(
        tblReservas.getValueAt(fila, 0).toString()
    );

    txtFechaInicio.setText(
        tblReservas.getValueAt(fila, 3).toString()
    );

    txtFechaFin.setText(
        tblReservas.getValueAt(fila, 4).toString()
    );

    cbEstado.setSelectedItem(
        tblReservas.getValueAt(fila, 5).toString()
    );

    txtFechaCreacion.setText(
        tblReservas.getValueAt(fila, 6).toString()
    );
}
    }//GEN-LAST:event_tblReservasMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

    try {

        SimpleDateFormat formato =
            new SimpleDateFormat("yyyy-MM-dd");

        Reserva obj = new Reserva();

        String clienteTexto =
            cbCliente.getSelectedItem().toString();

        int clienteId =
            Integer.parseInt(
                clienteTexto.split(" - ")[0]
            );

        String vehiculoTexto =
            cbVehiculo.getSelectedItem().toString();

        int vehiculoId =
            Integer.parseInt(
                vehiculoTexto.split(" - ")[0]
            );

        obj.setId(idReserva);

        obj.setClienteId(clienteId);

        obj.setVehiculoId(vehiculoId);

        obj.setFechaInicio(
            formato.parse(
                txtFechaInicio.getText()
            )
        );

        obj.setFechaFin(
            formato.parse(
                txtFechaFin.getText()
            )
        );

        obj.setEstado(
            cbEstado.getSelectedItem().toString()
        );

        obj.setFechaCreacion(
            formato.parse(
                txtFechaCreacion.getText()
            )
        );

        ReservaDAO dao = new ReservaDAO();

        if (dao.actualizar(obj)) {

            JOptionPane.showMessageDialog(
                null,
                "Reserva actualizada"
            );

            listar();

        } else {

            JOptionPane.showMessageDialog(
                null,
                "Error al actualizar"
            );
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
            null,
            "Formato incorrecto. Usa yyyy-MM-dd"
        );
    }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
     ReservaDAO dao = new ReservaDAO();

    if (idReserva == 0) {

        JOptionPane.showMessageDialog(
            null,
            "Selecciona una reserva"
        );

        return;
    }

    int opcion = JOptionPane.showConfirmDialog(
        null,
        "¿Deseas eliminar la reserva?"
    );

    if (opcion == 0) {

        if (dao.eliminar(idReserva)) {

            JOptionPane.showMessageDialog(
                null,
                "Reserva eliminada"
            );

            listar();

            limpiar();

        } else {

            JOptionPane.showMessageDialog(
                null,
                "Error al eliminar"
            );
        }
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
           limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReservas;
    private javax.swing.JTextField txtFechaCreacion;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    // End of variables declaration//GEN-END:variables
}
